export { default as GOOGLE_LOGO } from './logo_google.png';
export { default as USER_AVATAR } from './user_avatar.png';
export { default as DISCONNECTED } from './disconnected.png';
export { default as LOCATION } from './location.png';
export { default as Summary } from './summary.png';
export { default as BriefCase } from './briefcase.png';
export { default as LanguageCenter } from './language-center.png';
export { default as MagicHat } from './magic-hat.png';
export { default as ProfileCoverImage } from './profile_cover_image.jpg';