export enum PERMISSION {
  // USER
  VIEW_PROFILE = 'VIEW_PROFILE',
  EDIT_PROFILE = 'EDIT_PROFILE',
  VIEW_RESUME = 'VIEW_RESUME',
  UPLOAD_RESUME = 'UPLOAD_RESUME',
  DELETE_RESUME = 'DELETE_RESUME',
  VIEW_DESIRED_JOB = 'VIEW_DESIRED_JOB',
  EDIT_DESIRED_JOB = 'EDIT_DESIRED_JOB',
  VIEW_APPLIED_JOB = 'VIEW_APPLIED_JOB',
  VIEW_EMPLOYER_APPROACH = 'VIEW_EMPLOYER_APPROACH',
  USER_VIEW_ACCOUNT = 'USER_VIEW_ACCOUNT',
  USER_UPDATE_ACCOUNT = 'USER_UPDATE_ACCOUNT',
  USER_SIGN_IN = 'USER_SIGN_IN',
  USER_SIGN_UP = 'USER_SIGN_UP',
  // EMPLOYER
  VIEW_EMPLOYER_DASHBOARD = 'VIEW_EMPLOYER_DASHBOARD',
  VIEW_CANDIDATES = 'VIEW_CANDIDATES',
  POST_JOB = 'POST_JOB',
  VIEW_RECRUITMENT = 'VIEW_RECRUITMENT',
  EMPLOYER_SIGN_IN = 'EMPLOYER_SIGN_IN',
  EMPLOYER_SIGN_UP = 'EMPLOYER_SIGN_UP',
  // Admin
  VIEW_ADMIN_DASHBOARD = 'VIEW_ADMIN_DASHBOARD',
  // OTHERS
  LOGOUT = 'LOGOUT',
}
