import {
  AccountBookOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  CalendarOutlined,
  CheckCircleTwoTone,
  CloseOutlined,
  DeleteOutlined,
  DollarOutlined,
  EditOutlined,
  EnvironmentOutlined,
  EyeInvisibleOutlined,
  EyeTwoTone,
  FilePdfOutlined,
  HomeOutlined,
  LoadingOutlined,
  LogoutOutlined,
  MailOutlined,
  ProfileOutlined,
  ReconciliationOutlined,
  SettingOutlined,
  ShopOutlined,
  SnippetsOutlined,
  TeamOutlined,
  UserOutlined,
  LockOutlined,
} from '@ant-design/icons';

const icons = {
  EyeTwoTone,
  ArrowLeftOutlined,
  EyeInvisibleOutlined,
  LoadingOutlined,
  CheckCircleTwoTone,
  UserOutlined,
  ProfileOutlined,
  SnippetsOutlined,
  LogoutOutlined,
  DollarOutlined,
  EnvironmentOutlined,
  TeamOutlined,
  AccountBookOutlined,
  ArrowRightOutlined,
  ReconciliationOutlined,
  CalendarOutlined,
  DeleteOutlined,
  EditOutlined,
  FilePdfOutlined,
  SettingOutlined,
  ShopOutlined,
  HomeOutlined,
  CloseOutlined,
  MailOutlined,
  LockOutlined,
};

export default icons;
